name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - '.github/workflows/deploy.yml'

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Git config
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Prepare deployment folder
      run: |
        if (Test-Path deployment) { Remove-Item -Recurse -Force deployment }
        New-Item -ItemType Directory -Path deployment

      shell: pwsh

    - name: Combine CSS into deployment folder
      shell: pwsh
      run: |
        $DEPLOY_PATH = "$PWD\deployment"
        $COMBINED_CSS_PATH = Join-Path $DEPLOY_PATH "bundle.css"
        New-Item -ItemType File -Path $COMBINED_CSS_PATH -Force | Out-Null
        Get-ChildItem -Path "$PWD\src" -Filter *.css -File -Recurse |
          Sort-Object Name |
          ForEach-Object {
            Get-Content $_.FullName | Add-Content -Path $COMBINED_CSS_PATH
            Add-Content -Path $COMBINED_CSS_PATH -Value "`r`n"
          }

    - name: Combine HTML and JS into deployment folder
      shell: pwsh
      run: |
        $DEPLOY_PATH = "$PWD\deployment"
        $COMBINED_JS_PATH = Join-Path $DEPLOY_PATH "bundle.js"
        New-Item -ItemType File -Path $COMBINED_JS_PATH -Force | Out-Null

        Get-ChildItem -Path "$PWD\src\js" -Filter *.js -File -Recurse |
          Sort-Object Name |
          ForEach-Object {
            Get-Content $_.FullName | Add-Content -Path $COMBINED_JS_PATH
            Add-Content -Path $COMBINED_JS_PATH -Value "`r`n"
          }

    - name: Deploy deployment folder to gh-pages branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.PAT }}
        publish_branch: gh-pages
        publish_dir: deployment
